package com.tourcoo.training.entity.greendao;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import com.tourcoo.training.entity.account.CarInfo;
import com.tourcoo.training.entity.account.VehicleInfo;
import com.tourcoo.training.entity.account.UserInfo;

import com.tourcoo.training.entity.greendao.CarInfoDao;
import com.tourcoo.training.entity.greendao.VehicleInfoDao;
import com.tourcoo.training.entity.greendao.UserInfoDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig carInfoDaoConfig;
    private final DaoConfig vehicleInfoDaoConfig;
    private final DaoConfig userInfoDaoConfig;

    private final CarInfoDao carInfoDao;
    private final VehicleInfoDao vehicleInfoDao;
    private final UserInfoDao userInfoDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        carInfoDaoConfig = daoConfigMap.get(CarInfoDao.class).clone();
        carInfoDaoConfig.initIdentityScope(type);

        vehicleInfoDaoConfig = daoConfigMap.get(VehicleInfoDao.class).clone();
        vehicleInfoDaoConfig.initIdentityScope(type);

        userInfoDaoConfig = daoConfigMap.get(UserInfoDao.class).clone();
        userInfoDaoConfig.initIdentityScope(type);

        carInfoDao = new CarInfoDao(carInfoDaoConfig, this);
        vehicleInfoDao = new VehicleInfoDao(vehicleInfoDaoConfig, this);
        userInfoDao = new UserInfoDao(userInfoDaoConfig, this);

        registerDao(CarInfo.class, carInfoDao);
        registerDao(VehicleInfo.class, vehicleInfoDao);
        registerDao(UserInfo.class, userInfoDao);
    }
    
    public void clear() {
        carInfoDaoConfig.clearIdentityScope();
        vehicleInfoDaoConfig.clearIdentityScope();
        userInfoDaoConfig.clearIdentityScope();
    }

    public CarInfoDao getCarInfoDao() {
        return carInfoDao;
    }

    public VehicleInfoDao getVehicleInfoDao() {
        return vehicleInfoDao;
    }

    public UserInfoDao getUserInfoDao() {
        return userInfoDao;
    }

}
