package com.tourcoo.training.entity.greendao;

import android.database.Cursor;
import android.database.sqlite.SQLiteStatement;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.Property;
import org.greenrobot.greendao.internal.DaoConfig;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.database.DatabaseStatement;

import com.tourcoo.training.entity.account.VehicleInfo.VehicleInfoListConverter;
import java.util.List;

import com.tourcoo.training.entity.account.UserInfo;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table "USER_INFO".
*/
public class UserInfoDao extends AbstractDao<UserInfo, Void> {

    public static final String TABLENAME = "USER_INFO";

    /**
     * Properties of entity UserInfo.<br/>
     * Can be used for QueryBuilder and for referencing column names.
     */
    public static class Properties {
        public final static Property AccessToken = new Property(0, String.class, "AccessToken", false, "ACCESS_TOKEN");
        public final static Property Enabled = new Property(1, int.class, "Enabled", false, "ENABLED");
        public final static Property FVEnable = new Property(2, int.class, "FVEnable", false, "FVENABLE");
        public final static Property UserType = new Property(3, int.class, "UserType", false, "USER_TYPE");
        public final static Property IsAuthenticated = new Property(4, int.class, "IsAuthenticated", false, "IS_AUTHENTICATED");
        public final static Property Status = new Property(5, int.class, "Status", false, "STATUS");
        public final static Property IndustryCateID = new Property(6, String.class, "IndustryCateID", false, "INDUSTRY_CATE_ID");
        public final static Property Name = new Property(7, String.class, "Name", false, "NAME");
        public final static Property CoinsTotal = new Property(8, double.class, "CoinsTotal", false, "COINS_TOTAL");
        public final static Property CoinsRemain = new Property(9, double.class, "CoinsRemain", false, "COINS_REMAIN");
        public final static Property Avatar = new Property(10, String.class, "Avatar", false, "AVATAR");
        public final static Property Phone = new Property(11, String.class, "Phone", false, "PHONE");
        public final static Property IDCard = new Property(12, String.class, "IDCard", false, "IDCARD");
        public final static Property IDCardUrl = new Property(13, String.class, "IDCardUrl", false, "IDCARD_URL");
        public final static Property CompanyName = new Property(14, String.class, "CompanyName", false, "COMPANY_NAME");
        public final static Property IsMandatoryUpdate = new Property(15, double.class, "IsMandatoryUpdate", false, "IS_MANDATORY_UPDATE");
        public final static Property OnlineLearnProgress = new Property(16, double.class, "OnlineLearnProgress", false, "ONLINE_LEARN_PROGRESS");
        public final static Property OnsiteLearnProgress = new Property(17, double.class, "OnsiteLearnProgress", false, "ONSITE_LEARN_PROGRESS");
        public final static Property MonthRanking = new Property(18, String.class, "MonthRanking", false, "MONTH_RANKING");
        public final static Property Vehicles = new Property(19, String.class, "Vehicles", false, "VEHICLES");
    }

    private final VehicleInfoListConverter VehiclesConverter = new VehicleInfoListConverter();

    public UserInfoDao(DaoConfig config) {
        super(config);
    }
    
    public UserInfoDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
    }

    /** Creates the underlying database table. */
    public static void createTable(Database db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "\"USER_INFO\" (" + //
                "\"ACCESS_TOKEN\" TEXT," + // 0: AccessToken
                "\"ENABLED\" INTEGER NOT NULL ," + // 1: Enabled
                "\"FVENABLE\" INTEGER NOT NULL ," + // 2: FVEnable
                "\"USER_TYPE\" INTEGER NOT NULL ," + // 3: UserType
                "\"IS_AUTHENTICATED\" INTEGER NOT NULL ," + // 4: IsAuthenticated
                "\"STATUS\" INTEGER NOT NULL ," + // 5: Status
                "\"INDUSTRY_CATE_ID\" TEXT," + // 6: IndustryCateID
                "\"NAME\" TEXT," + // 7: Name
                "\"COINS_TOTAL\" REAL NOT NULL ," + // 8: CoinsTotal
                "\"COINS_REMAIN\" REAL NOT NULL ," + // 9: CoinsRemain
                "\"AVATAR\" TEXT," + // 10: Avatar
                "\"PHONE\" TEXT," + // 11: Phone
                "\"IDCARD\" TEXT," + // 12: IDCard
                "\"IDCARD_URL\" TEXT," + // 13: IDCardUrl
                "\"COMPANY_NAME\" TEXT," + // 14: CompanyName
                "\"IS_MANDATORY_UPDATE\" REAL NOT NULL ," + // 15: IsMandatoryUpdate
                "\"ONLINE_LEARN_PROGRESS\" REAL NOT NULL ," + // 16: OnlineLearnProgress
                "\"ONSITE_LEARN_PROGRESS\" REAL NOT NULL ," + // 17: OnsiteLearnProgress
                "\"MONTH_RANKING\" TEXT," + // 18: MonthRanking
                "\"VEHICLES\" TEXT);"); // 19: Vehicles
    }

    /** Drops the underlying database table. */
    public static void dropTable(Database db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "\"USER_INFO\"";
        db.execSQL(sql);
    }

    @Override
    protected final void bindValues(DatabaseStatement stmt, UserInfo entity) {
        stmt.clearBindings();
 
        String AccessToken = entity.getAccessToken();
        if (AccessToken != null) {
            stmt.bindString(1, AccessToken);
        }
        stmt.bindLong(2, entity.getEnabled());
        stmt.bindLong(3, entity.getFVEnable());
        stmt.bindLong(4, entity.getUserType());
        stmt.bindLong(5, entity.getIsAuthenticated());
        stmt.bindLong(6, entity.getStatus());
 
        String IndustryCateID = entity.getIndustryCateID();
        if (IndustryCateID != null) {
            stmt.bindString(7, IndustryCateID);
        }
 
        String Name = entity.getName();
        if (Name != null) {
            stmt.bindString(8, Name);
        }
        stmt.bindDouble(9, entity.getCoinsTotal());
        stmt.bindDouble(10, entity.getCoinsRemain());
 
        String Avatar = entity.getAvatar();
        if (Avatar != null) {
            stmt.bindString(11, Avatar);
        }
 
        String Phone = entity.getPhone();
        if (Phone != null) {
            stmt.bindString(12, Phone);
        }
 
        String IDCard = entity.getIDCard();
        if (IDCard != null) {
            stmt.bindString(13, IDCard);
        }
 
        String IDCardUrl = entity.getIDCardUrl();
        if (IDCardUrl != null) {
            stmt.bindString(14, IDCardUrl);
        }
 
        String CompanyName = entity.getCompanyName();
        if (CompanyName != null) {
            stmt.bindString(15, CompanyName);
        }
        stmt.bindDouble(16, entity.getIsMandatoryUpdate());
        stmt.bindDouble(17, entity.getOnlineLearnProgress());
        stmt.bindDouble(18, entity.getOnsiteLearnProgress());
 
        String MonthRanking = entity.getMonthRanking();
        if (MonthRanking != null) {
            stmt.bindString(19, MonthRanking);
        }
 
        List Vehicles = entity.getVehicles();
        if (Vehicles != null) {
            stmt.bindString(20, VehiclesConverter.convertToDatabaseValue(Vehicles));
        }
    }

    @Override
    protected final void bindValues(SQLiteStatement stmt, UserInfo entity) {
        stmt.clearBindings();
 
        String AccessToken = entity.getAccessToken();
        if (AccessToken != null) {
            stmt.bindString(1, AccessToken);
        }
        stmt.bindLong(2, entity.getEnabled());
        stmt.bindLong(3, entity.getFVEnable());
        stmt.bindLong(4, entity.getUserType());
        stmt.bindLong(5, entity.getIsAuthenticated());
        stmt.bindLong(6, entity.getStatus());
 
        String IndustryCateID = entity.getIndustryCateID();
        if (IndustryCateID != null) {
            stmt.bindString(7, IndustryCateID);
        }
 
        String Name = entity.getName();
        if (Name != null) {
            stmt.bindString(8, Name);
        }
        stmt.bindDouble(9, entity.getCoinsTotal());
        stmt.bindDouble(10, entity.getCoinsRemain());
 
        String Avatar = entity.getAvatar();
        if (Avatar != null) {
            stmt.bindString(11, Avatar);
        }
 
        String Phone = entity.getPhone();
        if (Phone != null) {
            stmt.bindString(12, Phone);
        }
 
        String IDCard = entity.getIDCard();
        if (IDCard != null) {
            stmt.bindString(13, IDCard);
        }
 
        String IDCardUrl = entity.getIDCardUrl();
        if (IDCardUrl != null) {
            stmt.bindString(14, IDCardUrl);
        }
 
        String CompanyName = entity.getCompanyName();
        if (CompanyName != null) {
            stmt.bindString(15, CompanyName);
        }
        stmt.bindDouble(16, entity.getIsMandatoryUpdate());
        stmt.bindDouble(17, entity.getOnlineLearnProgress());
        stmt.bindDouble(18, entity.getOnsiteLearnProgress());
 
        String MonthRanking = entity.getMonthRanking();
        if (MonthRanking != null) {
            stmt.bindString(19, MonthRanking);
        }
 
        List Vehicles = entity.getVehicles();
        if (Vehicles != null) {
            stmt.bindString(20, VehiclesConverter.convertToDatabaseValue(Vehicles));
        }
    }

    @Override
    public Void readKey(Cursor cursor, int offset) {
        return null;
    }    

    @Override
    public UserInfo readEntity(Cursor cursor, int offset) {
        UserInfo entity = new UserInfo( //
            cursor.isNull(offset + 0) ? null : cursor.getString(offset + 0), // AccessToken
            cursor.getInt(offset + 1), // Enabled
            cursor.getInt(offset + 2), // FVEnable
            cursor.getInt(offset + 3), // UserType
            cursor.getInt(offset + 4), // IsAuthenticated
            cursor.getInt(offset + 5), // Status
            cursor.isNull(offset + 6) ? null : cursor.getString(offset + 6), // IndustryCateID
            cursor.isNull(offset + 7) ? null : cursor.getString(offset + 7), // Name
            cursor.getDouble(offset + 8), // CoinsTotal
            cursor.getDouble(offset + 9), // CoinsRemain
            cursor.isNull(offset + 10) ? null : cursor.getString(offset + 10), // Avatar
            cursor.isNull(offset + 11) ? null : cursor.getString(offset + 11), // Phone
            cursor.isNull(offset + 12) ? null : cursor.getString(offset + 12), // IDCard
            cursor.isNull(offset + 13) ? null : cursor.getString(offset + 13), // IDCardUrl
            cursor.isNull(offset + 14) ? null : cursor.getString(offset + 14), // CompanyName
            cursor.getDouble(offset + 15), // IsMandatoryUpdate
            cursor.getDouble(offset + 16), // OnlineLearnProgress
            cursor.getDouble(offset + 17), // OnsiteLearnProgress
            cursor.isNull(offset + 18) ? null : cursor.getString(offset + 18), // MonthRanking
            cursor.isNull(offset + 19) ? null : VehiclesConverter.convertToEntityProperty(cursor.getString(offset + 19)) // Vehicles
        );
        return entity;
    }
     
    @Override
    public void readEntity(Cursor cursor, UserInfo entity, int offset) {
        entity.setAccessToken(cursor.isNull(offset + 0) ? null : cursor.getString(offset + 0));
        entity.setEnabled(cursor.getInt(offset + 1));
        entity.setFVEnable(cursor.getInt(offset + 2));
        entity.setUserType(cursor.getInt(offset + 3));
        entity.setIsAuthenticated(cursor.getInt(offset + 4));
        entity.setStatus(cursor.getInt(offset + 5));
        entity.setIndustryCateID(cursor.isNull(offset + 6) ? null : cursor.getString(offset + 6));
        entity.setName(cursor.isNull(offset + 7) ? null : cursor.getString(offset + 7));
        entity.setCoinsTotal(cursor.getDouble(offset + 8));
        entity.setCoinsRemain(cursor.getDouble(offset + 9));
        entity.setAvatar(cursor.isNull(offset + 10) ? null : cursor.getString(offset + 10));
        entity.setPhone(cursor.isNull(offset + 11) ? null : cursor.getString(offset + 11));
        entity.setIDCard(cursor.isNull(offset + 12) ? null : cursor.getString(offset + 12));
        entity.setIDCardUrl(cursor.isNull(offset + 13) ? null : cursor.getString(offset + 13));
        entity.setCompanyName(cursor.isNull(offset + 14) ? null : cursor.getString(offset + 14));
        entity.setIsMandatoryUpdate(cursor.getDouble(offset + 15));
        entity.setOnlineLearnProgress(cursor.getDouble(offset + 16));
        entity.setOnsiteLearnProgress(cursor.getDouble(offset + 17));
        entity.setMonthRanking(cursor.isNull(offset + 18) ? null : cursor.getString(offset + 18));
        entity.setVehicles(cursor.isNull(offset + 19) ? null : VehiclesConverter.convertToEntityProperty(cursor.getString(offset + 19)));
     }
    
    @Override
    protected final Void updateKeyAfterInsert(UserInfo entity, long rowId) {
        // Unsupported or missing PK type
        return null;
    }
    
    @Override
    public Void getKey(UserInfo entity) {
        return null;
    }

    @Override
    public boolean hasKey(UserInfo entity) {
        // TODO
        return false;
    }

    @Override
    protected final boolean isEntityUpdateable() {
        return true;
    }
    
}
